import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const tajawal = localFont({
  src: "./fonts/Tajawal-Regular.ttf",
  variable: "--font-tajawal",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Arab Code Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${tajawal.variable}`}>{children}</body>
    </html>
  );
}
